// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function ClearHistory():Promise<void>;

export function DeleteHistory(arg1:number):Promise<void>;

export function GetAboutInfo():Promise<desktop.AboutInfo>;

export function GetCurrentVersion():Promise<string>;

export function GetHistory():Promise<Array<desktop.HistoryItem>>;

export function GetHistoryAudio(arg1:number):Promise<desktop.HistoryAudioResponse>;

export function GetLang():Promise<string>;

export function GetSettings():Promise<desktop.Settings>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function SaveHistory(arg1:desktop.SaveHistoryRequest):Promise<void>;

export function SaveSettings(arg1:desktop.Settings):Promise<void>;

export function SelectFolder():Promise<string>;

export function SetLang(arg1:string):Promise<void>;

export function StartSynthesizeSpeechStream(arg1:desktop.StreamTTSRequest):Promise<void>;

export function SynthesizeSpeech(arg1:desktop.TTSRequest):Promise<desktop.TTSResponse>;
