// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['desktop']['App']['ClearHistory']();
}

export function DeleteHistory(arg1) {
  return window['go']['desktop']['App']['DeleteHistory'](arg1);
}

export function GetAboutInfo() {
  return window['go']['desktop']['App']['GetAboutInfo']();
}

export function GetCurrentVersion() {
  return window['go']['desktop']['App']['GetCurrentVersion']();
}

export function GetHistory() {
  return window['go']['desktop']['App']['GetHistory']();
}

export function GetHistoryAudio(arg1) {
  return window['go']['desktop']['App']['GetHistoryAudio'](arg1);
}

export function GetLang() {
  return window['go']['desktop']['App']['GetLang']();
}

export function GetSettings() {
  return window['go']['desktop']['App']['GetSettings']();
}

export function OpenFile(arg1) {
  return window['go']['desktop']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['desktop']['App']['OpenFolder'](arg1);
}

export function SaveHistory(arg1) {
  return window['go']['desktop']['App']['SaveHistory'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['desktop']['App']['SaveSettings'](arg1);
}

export function SearchHistory(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SearchHistory'](arg1, arg2, arg3);
}

export function SelectFolder() {
  return window['go']['desktop']['App']['SelectFolder']();
}

export function SetLang(arg1) {
  return window['go']['desktop']['App']['SetLang'](arg1);
}

export function StartSynthesizeSpeechStream(arg1) {
  return window['go']['desktop']['App']['StartSynthesizeSpeechStream'](arg1);
}

export function SynthesizeSpeech(arg1) {
  return window['go']['desktop']['App']['SynthesizeSpeech'](arg1);
}
